version: '3.4'
services: 
  config-server:
    image: datasite/config-server:latest
    ports:
      - 8888:8888
    volumes:
      - ${PWD}/ds1-configurations:/config
    environment:
      - CONFIG_REPO_PATH=file:///config
      - ACTIVE_PCF_ENVIRONMENT=${ACTIVE_PCF_ENVIRONMENT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
  mongo:
    container_name: mongo
    image: mongo:bionic
    ports: 
      - 27017:27017
  rabbit-mq:
    container_name: rabbit-mq
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
